added back into configure.ac the check for gperf

diff --git a/gtkwave3/configure b/gtkwave3/configure
--- a/gtkwave3/configure
+++ b/gtkwave3/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT AET2_CFLAGS AET2_LDADD CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB LIBZ_CFLAGS LIBZ_LDADD LIBZ_DIR LIBBZ2_CFLAGS LIBBZ2_LDADD LIBBZ2_DIR GTK_CONFIG PKG_CONFIG ac_pt_PKG_CONFIG GTK_CFLAGS GTK_LIBS ALLOCA CPP EGREP LIBOBJS POW_LIB LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT AET2_CFLAGS AET2_LDADD CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEX LEXLIB LEX_OUTPUT_ROOT RANLIB ac_ct_RANLIB GPERF LIBZ_CFLAGS LIBZ_LDADD LIBZ_DIR LIBBZ2_CFLAGS LIBBZ2_LDADD LIBBZ2_DIR GTK_CONFIG PKG_CONFIG ac_pt_PKG_CONFIG GTK_CFLAGS GTK_LIBS ALLOCA CPP EGREP LIBOBJS POW_LIB LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3407,13 +3407,57 @@ fi
 # gperf only needed if the user updates the gperf data
 # files which only developers will be doing...
 #
-# AC_PATH_PROG(GPERF, [gperf], [notfound])
-# if test "$GPERF" = "notfound" ; then
-#	AC_MSG_ERROR([Couldn't find a usable gperf program.
-# Please install gperf which is available from
-# ftp://ftp.gnu.org/pub/gnu/gperf/
-# ])
-# fi
+# Extract the first word of "gperf", so it can be a program name with args.
+set dummy gperf; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_GPERF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GPERF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GPERF="$GPERF" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_GPERF="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_GPERF" && ac_cv_path_GPERF="notfound"
+  ;;
+esac
+fi
+GPERF=$ac_cv_path_GPERF
+
+if test -n "$GPERF"; then
+  echo "$as_me:$LINENO: result: $GPERF" >&5
+echo "${ECHO_T}$GPERF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "$GPERF" = "notfound" ; then
+	{ { echo "$as_me:$LINENO: error: Couldn't find a usable gperf program.
+Please install gperf which is available from
+ftp://ftp.gnu.org/pub/gnu/gperf/
+" >&5
+echo "$as_me: error: Couldn't find a usable gperf program.
+Please install gperf which is available from
+ftp://ftp.gnu.org/pub/gnu/gperf/
+" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 # Checks for libraries.
 
@@ -10457,6 +10501,7 @@ s,@LEXLIB@,$LEXLIB,;t t
 s,@LEX_OUTPUT_ROOT@,$LEX_OUTPUT_ROOT,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
+s,@GPERF@,$GPERF,;t t
 s,@LIBZ_CFLAGS@,$LIBZ_CFLAGS,;t t
 s,@LIBZ_LDADD@,$LIBZ_LDADD,;t t
 s,@LIBZ_DIR@,$LIBZ_DIR,;t t
