added libbz2 to configure.ac plus header checking for zlib.h/bzlib.h

diff --git a/gtkwave3/configure b/gtkwave3/configure
--- a/gtkwave3/configure
+++ b/gtkwave3/configure
@@ -880,6 +880,10 @@ Optional Features:
                           already be installed on your system.  Default is to
                           first look for an installed libz and fall back to
                           using the bundled one.
+  --enable-local-libbz2   Use the bundled libbz2 instead of any libbz2 which may
+                          already be installed on your system.  Default is to
+                          first look for an installed libbz2 and fall back to
+                          using the bundled one.
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -4049,6 +4053,62 @@ need_libz=no
 LIBZ_LDADD=
 LIBZ_CFLAGS=
 if test "X$force_bundled_libz" != "Xyes" ; then
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <zlib.h>
+int
+main ()
+{
+gzdopen(0,"rb");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+need_libz=yes
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	if test "$need_libz" = "yes" -a "X$force_system_libz" = "Xyes" ; then
+		{ { echo "$as_me:$LINENO: error:
+You have disabled building the bundled libz but no system libz headers
+could be found.  Either allow building the bundled libz (by not using
+--disable-local-libz) or make sure your system has a libz installed" >&5
+echo "$as_me: error:
+You have disabled building the bundled libz but no system libz headers
+could be found.  Either allow building the bundled libz (by not using
+--disable-local-libz) or make sure your system has a libz installed" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 	echo "$as_me:$LINENO: checking for gzread in -lz" >&5
 echo $ECHO_N "checking for gzread in -lz... $ECHO_C" >&6
 if test "${ac_cv_lib_z_gzread+set}" = set; then
@@ -4134,10 +4194,78 @@ else
 	need_libz=yes
 fi
 
+# Check whether --enable-local-libbz2 or --disable-local-libbz2 was given.
+if test "${enable_local_libbz2+set}" = set; then
+  enableval="$enable_local_libbz2"
+
+if test "X$enable_local_libbz2" = "Xno" ; then
+	force_system_libbz2=yes
+else
+	force_bundled_libbz2=yes
+fi
+
+fi;
+
 need_libbz2=no
 LIBBZ2_LDADD=
 LIBBZ2_CFLAGS=
 if test "X$force_bundled_libbz2" != "Xyes" ; then
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <bzlib.h>
+int
+main ()
+{
+BZ2_bzdopen(0,"rb");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+need_libbz2=yes
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	if test "$need_libbz2" = "yes" -a "X$force_system_libbz2" = "Xyes" ; then
+		{ { echo "$as_me:$LINENO: error:
+You have disabled building the bundled libbz2 but no system libbz2 headers
+could be found.  Either allow building the bundled libbz2 (by not using
+--disable-local-libbz2) or make sure your system has a libbz2 installed" >&5
+echo "$as_me: error:
+You have disabled building the bundled libbz2 but no system libbz2 headers
+could be found.  Either allow building the bundled libbz2 (by not using
+--disable-local-libbz2) or make sure your system has a libbz2 installed" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 	echo "$as_me:$LINENO: checking for BZ2_bzread in -lbz2" >&5
 echo $ECHO_N "checking for BZ2_bzread in -lbz2... $ECHO_C" >&6
 if test "${ac_cv_lib_bz2_BZ2_bzread+set}" = set; then
